# Generating the November 2025 Schedule 
**This notebook builds the November 2025 schedule for Internal Medicine, Pediatrics, and Family Practice using the scheduler.**

In [1]:
## Setup and Imports
import sys
from pathlib import Path
import os
import pandas as pd
from datetime import date, timedelta

In [2]:
# Add project root (one level up from 'notebooks') to sys.path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [3]:
# Import our scheduling engine
from engine.engine import create_im_schedule, create_peds_schedule, create_fp_schedule

# Import calendar generation
from utils.calendar_formatter import create_html_calendar

## Internal Medicine Schedule

In [4]:
schedule_df, provider_summary_df, solution_status = create_im_schedule(
    config_path = '../config/internal_medicine.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    start_date = date(2025, 11, 3),
    end_date = date(2025, 11, 28),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:57:59,492 - engine.engine - INFO - Creating schedule for Internal Medicine from 2025-11-03 to 2025-11-28
2025-06-22 13:57:59,493 - engine.engine - INFO - Parsing input files
2025-06-22 13:57:59,501 - engine.engine - INFO - Building calendar
2025-06-22 13:57:59,501 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:57:59,502 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:57:59,515 - engine.engine - WARNING - No feasible solution found with min_providers = 4
2025-06-22 13:57:59,515 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 3
2025-06-22 13:57:59,537 - engine.engine - INFO - Found optimal solution with min_providers = 3
2025-06-22 13:57:59,538 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 3

In [5]:
schedule_df.to_csv('../output/november_25/internal_medicine/schedule_df.csv', index = False)
schedule_df

,date,day_of_week,session,providers,count
0,2025-11-03,Monday,morning,"Mcnett,Mcrae,Tanay",3
1,2025-11-03,Monday,afternoon,"Mcnett,Mcrae,Tanay",3
2,2025-11-04,Tuesday,morning,"Bornstein,Mcnett,Mcrae,Selig,Tanay",5
3,2025-11-04,Tuesday,afternoon,"Bornstein,Mcnett,Miles,Selig,Tanay",5
4,2025-11-05,Wednesday,morning,"Bornstein,Mcnett,Selig,Tanay,Wadlin",5
5,2025-11-05,Wednesday,afternoon,"Bornstein,Mcnett,Tanay,Wadlin",4
6,2025-11-06,Thursday,afternoon,"Mcnett,Mcrae,Selig,Stewart,Wadlin",5
7,2025-11-07,Friday,morning,"Mcnett,Mcrae,Selig",3
8,2025-11-07,Friday,afternoon,"Mcnett,Mcrae,Selig",3
9,2025-11-10,Monday,morning,"Bornstein,Mcnett,Mcrae,Selig",4
10,2025-11-10,Monday,afternoon,"Bornstein,Mcnett,Mcrae,Selig",4
11,2025-11-12,Wednesday,morning,"Bornstein,Miles,Stewart,Tanay,Wadlin",5
12,2025-11-12,Wednesday,afternoon,"Mcnett,Miles,Stewart,Tanay,Wadlin",5
13,2025-11-13,Thursday,afternoon,"Mcnett,Miles,Selig,Tanay,Wadlin",5
14,2025-11-14,Friday,morning,"Mcnett,Selig,Stewart,Tanay,Wadlin",5
15,2025-11-14,Friday,afternoon,"Bornstein,Mcrae,Selig,Stewart,Tanay",5
16,2025-11-17,Monday,morning,"Mcnett,Selig,Wadlin",3
17,2025-11-17,Monday,afternoon,"Mcnett,Selig,Stewart,Wadlin",4
18,2025-11-18,Tuesday,morning,"Mcnett,Mcrae,Tanay,Wadlin",4
19,2025-11-18,Tuesday,afternoon,"Mcnett,Mcrae,Tanay",3
20,2025-11-19,Wednesday,morning,"Mcnett,Mcrae,Stewart,Tanay,Wadlin",5
21,2025-11-19,Wednesday,afternoon,"Mcnett,Mcrae,Selig,Tanay",4
22,2025-11-20,Thursday,afternoon,"Mcnett,Selig,Stewart,Tanay,Wadlin",5
23,2025-11-21,Friday,morning,"Mcnett,Mcrae,Selig",3
24,2025-11-21,Friday,afternoon,"Mcnett,Mcrae,Selig,Stewart,Tanay",5
25,2025-11-24,Monday,morning,"Mcnett,Stewart,Tanay",3
26,2025-11-24,Monday,afternoon,"Mcnett,Stewart,Tanay",3
27,2025-11-25,Tuesday,morning,"Mcnett,Selig,Stewart",3
28,2025-11-25,Tuesday,afternoon,"Mcnett,Selig,Stewart",3
29,2025-11-26,Wednesday,morning,"Mcnett,Selig,Tanay",3
30,2025-11-26,Wednesday,afternoon,"Mcnett,Selig,Tanay",3
31,2025-11-28,Friday,morning,"Mcnett,Selig,Tanay",3
32,2025-11-28,Friday,afternoon,"Mcnett,Selig,Tanay",3

In [6]:
provider_summary_df.to_csv('../output/november_25/internal_medicine/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_45,week_46,week_47,week_48,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Bornstein,"4, 4","4, 3","0, 0","0, 0",8,3,4,4
1,Mcnett,"9, 6","5, 2","9, 6","8, 8",31,0,14,17
2,Mcrae,"6, 3","3, 2","6, 4","0, 0",15,2,7,8
3,Miles,"1, 1","3, 2","0, 0","0, 0",4,4,1,3
4,Selig,"6, 3","5, 3","6, 3","6, 6",23,2,10,13
5,Stewart,"1, 1","4, 2","4, 1","4, 4",13,3,5,8
6,Tanay,"6, 6","5, 3","6, 4","6, 4",23,3,10,13
7,Wadlin,"3, 2","4, 2","5, 3","0, 0",12,4,6,6

In [7]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 3,
 'Objective value': 3700.0,
 'Solve time': '0.011152 seconds',
 'Branches': 412,
 'Conflicts': 0}

In [8]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/internal_medicine.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Internal Medicine Calendar', 
                     output_dir = '../output/november_25/internal_medicine',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-11-03 to 2025-11-28
Processing 33 schedule entries...
Processed schedule data for 18 unique dates
Filtered to 111 leave requests for this department
Processing 111 leave requests...
Processed leave requests for 55 unique dates
Filtered to 11 inpatient assignments for this department
Processing 11 inpatient assignments...
Processed inpatient assignments for 70 unique dates
Found 4 weeks containing scheduled dates
Calendar saved to: ../output/november_25/internal_medicine/calendar.html

## Pediatric Schedule

In [9]:
schedule_df, provider_summary_df, call_summary_df, solution_status = create_peds_schedule(
    config_path = '../config/pediatrics.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    start_date = date(2025, 11, 2),
    end_date = date(2025, 11, 29),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:57:59,585 - engine.engine - INFO - Creating schedule for Pediatric from 2025-11-02 to 2025-11-29
2025-06-22 13:57:59,586 - engine.engine - INFO - Parsing input files
2025-06-22 13:57:59,593 - engine.engine - INFO - Building calendar
2025-06-22 13:57:59,593 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:57:59,594 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:57:59,621 - engine.engine - WARNING - No feasible solution found with min_providers = 4
2025-06-22 13:57:59,621 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 3
2025-06-22 13:57:59,647 - engine.engine - WARNING - No feasible solution found with min_providers = 3
2025-06-22 13:57:59,647 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 2
2025-06-22 13:57:59,684 - engine.engine - INFO - Found optimal solution with min_providers = 2
2025-06-22 13:57:59,687 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 2

In [10]:
schedule_df.head(50)

          date day_of_week    session                       providers  count
0   2025-11-02      Sunday       call                          Bedele    NaN
1   2025-11-03      Monday    morning            Bedele,Mador,Sridhar    3.0
2   2025-11-03      Monday  afternoon                   Mador,Sridhar    2.0
3   2025-11-03      Monday       call                          Powell    NaN
4   2025-11-04     Tuesday    morning            Mador,Miller,Sridhar    3.0
5   2025-11-04     Tuesday  afternoon            Mador,Miller,Sridhar    3.0
6   2025-11-04     Tuesday       call                        Menachof    NaN
7   2025-11-05   Wednesday    morning     Bedele,Mador,Miller,Sridhar    4.0
8   2025-11-05   Wednesday  afternoon     Bedele,Mador,Miller,Sridhar    4.0
9   2025-11-05   Wednesday       call                          Miller    NaN
10  2025-11-06    Thursday  afternoon                 Bedele,Menachof    2.0
11  2025-11-06    Thursday       call                        Lichtman    NaN
12  2025-11-07      Friday    morning                   Bedele,Miller    2.0
13  2025-11-07      Friday  afternoon                   Bedele,Miller    2.0
14  2025-11-07      Friday       call                        Carrasco    NaN
15  2025-11-08    Saturday       call                        Carrasco    NaN
16  2025-11-09      Sunday       call                        Menachof    NaN
17  2025-11-10      Monday    morning            Bedele,Mador,Sridhar    3.0
18  2025-11-10      Monday  afternoon            Bedele,Mador,Sridhar    3.0
19  2025-11-10      Monday       call                          Bedele    NaN
20  2025-11-11     Tuesday       call                          Bedele    NaN
21  2025-11-12   Wednesday    morning           Bedele,Carrasco,Mador    3.0
22  2025-11-12   Wednesday  afternoon         Carrasco,Mador,Menachof    3.0
23  2025-11-12   Wednesday       call                        Menachof    NaN
24  2025-11-13    Thursday  afternoon           Bedele,Carrasco,Mador    3.0
25  2025-11-13    Thursday       call                          Powell    NaN
26  2025-11-14      Friday    morning                 Bedele,Menachof    2.0
27  2025-11-14      Friday  afternoon                 Bedele,Menachof    2.0
28  2025-11-14      Friday       call                          Miller    NaN
29  2025-11-15    Saturday       call                          Miller    NaN
30  2025-11-16      Sunday       call                        Lichtman    NaN
31  2025-11-17      Monday    morning                  Carrasco,Mador    2.0
32  2025-11-17      Monday  afternoon                  Carrasco,Mador    2.0
33  2025-11-17      Monday       call                          Powell    NaN
34  2025-11-18     Tuesday    morning  Carrasco,Miller,Snyder,Sridhar    4.0
35  2025-11-18     Tuesday  afternoon  Carrasco,Miller,Snyder,Sridhar    4.0
36  2025-11-18     Tuesday       call                          Miller    NaN
37  2025-11-19   Wednesday    morning  Carrasco,Miller,Snyder,Sridhar    4.0
38  2025-11-19   Wednesday  afternoon         Carrasco,Snyder,Sridhar    3.0
39  2025-11-19   Wednesday       call                            Shin    NaN
40  2025-11-20    Thursday  afternoon     Mador,Miller,Snyder,Sridhar    4.0
41  2025-11-20    Thursday       call                         Sridhar    NaN
42  2025-11-21      Friday    morning            Mador,Snyder,Sridhar    3.0
43  2025-11-21      Friday  afternoon                    Mador,Snyder    2.0
44  2025-11-21      Friday       call                          Bedele    NaN
45  2025-11-22    Saturday       call                          Bedele    NaN
46  2025-11-23      Sunday       call                           Mador    NaN
47  2025-11-24      Monday    morning             Mador,Miller,Snyder    3.0
48  2025-11-24      Monday  afternoon                   Miller,Snyder    2.0
49  2025-11-24      Monday       call                        Lichtman    NaN

In [11]:
# Get the current providers for session 11/17 PM
mask = (schedule_df['date'] == date(2025, 11, 17)) & (schedule_df['session'] == 'afternoon')
current_providers = schedule_df.loc[mask, 'providers'].iloc[0]

# Add Snyder
schedule_df.loc[mask, 'providers'] = current_providers + ',Snyder'

# Update provider_summary_df count for that day 
current_count = schedule_df.loc[mask, 'count'].iloc[0]
schedule_df.loc[mask, 'count'] = current_count + 1

In [12]:
schedule_df.to_csv('../output/november_25/pediatrics/schedule_df.csv', index = False)

In [13]:
provider_summary_df.to_csv('../output/november_25/pediatrics/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_45,week_46,week_47,week_48,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Bedele,"6, 3","6, 3","0, 0","0, 0",12,2,6,6
1,Carrasco,"0, 0","3, 2","6, 6","0, 0",9,4,4,5
2,Mador,"6, 6","5, 4","5, 3","6, 3",22,2,11,11
3,Menachof,"1, 1","3, 2","0, 0","0, 0",4,4,1,3
4,Miller,"6, 4","0, 0","4, 3","6, 6",16,4,8,8
5,Snyder,"0, 0","0, 0","7, 4","8, 8",15,3,7,8
6,Sridhar,"6, 6","2, 2","6, 4","0, 0",14,4,7,7

In [14]:
call_summary_df.to_csv('../output/november_25/pediatrics/call_summary_df.csv', index = False)
call_summary_df

   provider  week_44  week_45  week_46  week_47  week_48  total_call
0    Bedele        1        0        2        2        0           5
1  Carrasco        0        2        0        0        0           2
2  Lichtman        0        1        1        0        1           3
3     Mador        0        0        0        1        1           2
4  Menachof        0        2        1        0        2           5
5    Miller        0        1        2        1        2           6
6    Powell        0        1        1        1        0           3
7      Shin        0        0        0        1        0           1
8    Snyder        0        0        0        0        0           0
9   Sridhar        0        0        0        1        0           1

In [15]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 2,
 'Objective value': 8000.0,
 'Solve time': '0.013876 seconds',
 'Branches': 310,
 'Conflicts': 0}

In [16]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/pediatrics.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Pediatrics Calendar', 
                     output_dir = '../output/november_25/pediatrics',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-11-02 to 2025-11-29
Processing 61 schedule entries...
Processed schedule data for 28 unique dates
Filtered to 184 leave requests for this department
Processing 184 leave requests...
Processed leave requests for 75 unique dates
Filtered to 26 inpatient assignments for this department
Processing 26 inpatient assignments...
Processed inpatient assignments for 133 unique dates
Found 4 weeks containing scheduled dates
Calendar saved to: ../output/november_25/pediatrics/calendar.html

## Family Practice Schedule

In [17]:
schedule_df, provider_summary_df, solution_status = create_fp_schedule(
    config_path = '../config/family_practice.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    peds_schedule_path = '../output/november_25/pediatrics/schedule_df.csv',
    start_date = date(2025, 11, 3),
    end_date = date(2025, 11, 28),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:57:59,760 - engine.engine - INFO - Creating schedule for Family Practice from 2025-11-03 to 2025-11-28
2025-06-22 13:57:59,761 - engine.engine - INFO - Parsing input files
2025-06-22 13:57:59,767 - engine.engine - INFO - Loading pediatric schedule
2025-06-22 13:57:59,769 - engine.engine - INFO - Successfully loaded pediatric schedule with 61 rows
2025-06-22 13:57:59,770 - engine.engine - INFO - Building calendar
2025-06-22 13:57:59,770 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:57:59,770 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:57:59,808 - engine.engine - INFO - Found optimal solution with min_providers = 4
2025-06-22 13:57:59,811 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 4

In [18]:
schedule_df.to_csv('../output/november_25/family_practice/schedule_df.csv', index = False)
schedule_df

,date,day_of_week,session,providers,count
0,2025-11-03,Monday,morning,"Austin,Finnie,Powell,Salay,Suen",5
1,2025-11-03,Monday,afternoon,"Austin,Finnie,Powell,Salay,Suen",5
2,2025-11-04,Tuesday,morning,"Austin,Finnie,Mullenix,Powell,Suen",5
3,2025-11-04,Tuesday,afternoon,"Austin,Gelman,Lichtman,Mullenix,Salay",5
4,2025-11-05,Wednesday,morning,"Austin,Gelman,Mullenix,Powell,Salay",5
5,2025-11-05,Wednesday,afternoon,"Austin,Gelman,Lichtman,Mullenix,Salay",5
6,2025-11-06,Thursday,afternoon,"Bia,Finnie,Gelman,Mullenix,Salay",5
7,2025-11-07,Friday,morning,"Bia,Brush,Finnie,Lichtman,Suen",5
8,2025-11-07,Friday,afternoon,"Bia,Brush,Finnie,Mullenix,Suen",5
9,2025-11-10,Monday,morning,"Austin,Bia,Finnie,Lichtman,Mullenix",5
10,2025-11-10,Monday,afternoon,"Bia,Finnie,Lichtman,Mullenix,Suen",5
11,2025-11-12,Wednesday,morning,"Austin,Bia,Lichtman,Powell,Shin",5
12,2025-11-12,Wednesday,afternoon,"Bia,Finnie,Lichtman,Powell,Shin",5
13,2025-11-13,Thursday,afternoon,"Austin,Bia,Powell,Shin,Suen",5
14,2025-11-14,Friday,morning,"Brush,Lichtman,Mullenix,Powell,Suen",5
15,2025-11-14,Friday,afternoon,"Brush,Lichtman,Mullenix,Suen",4
16,2025-11-17,Monday,morning,"Bia,Finnie,Mullenix,Powell,Suen",5
17,2025-11-17,Monday,afternoon,"Bia,Finnie,Mullenix,Powell,Suen",5
18,2025-11-18,Tuesday,morning,"Bia,Finnie,Lichtman,Mullenix,Shin",5
19,2025-11-18,Tuesday,afternoon,"Finnie,Gelman,Lichtman,Mullenix,Shin",5
20,2025-11-19,Wednesday,morning,"Gelman,Lichtman,Powell,Salay,Shin",5
21,2025-11-19,Wednesday,afternoon,"Finnie,Lichtman,Salay,Shin,Suen",5
22,2025-11-20,Thursday,afternoon,"Finnie,Gelman,Lichtman,Powell,Salay",5
23,2025-11-21,Friday,morning,"Brush,Mullenix,Powell,Shin,Suen",5
24,2025-11-21,Friday,afternoon,"Bia,Brush,Mullenix,Shin,Suen",5
25,2025-11-24,Monday,morning,"Finnie,Lichtman,Mullenix,Salay",4
26,2025-11-24,Monday,afternoon,"Finnie,Lichtman,Mullenix,Shin",4
27,2025-11-25,Tuesday,morning,"Finnie,Mullenix,Salay,Shin",4
28,2025-11-25,Tuesday,afternoon,"Finnie,Mullenix,Salay,Shin",4
29,2025-11-26,Wednesday,morning,"Finnie,Lichtman,Mullenix,Salay",4
30,2025-11-26,Wednesday,afternoon,"Lichtman,Mullenix,Salay,Shin",4
31,2025-11-28,Friday,morning,"Brush,Finnie,Lichtman,Shin",4
32,2025-11-28,Friday,afternoon,"Brush,Lichtman,Salay,Shin",4

In [19]:
provider_summary_df.to_csv('../output/november_25/family_practice/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_45,week_46,week_47,week_48,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Austin,"6, 6","3, 1","0, 0","0, 0",9,4,5,4
1,Bia,"3, 3","5, 4","4, 3","0, 0",12,3,5,7
2,Brush,"2, 2","2, 2","2, 2","2, 2",8,4,4,4
3,Finnie,"6, 3","3, 2","6, 4","6, 5",21,2,10,11
4,Gelman,"4, 3","0, 0","3, 2","0, 0",7,4,2,5
5,Lichtman,"3, 1","6, 4","5, 4","6, 4",20,2,9,11
6,Mullenix,"6, 4","4, 2","6, 4","6, 6",22,2,10,12
7,Powell,"4, 3","4, 2","5, 2","0, 0",13,3,8,5
8,Salay,"6, 3","0, 0","3, 2","6, 4",15,3,6,9
9,Shin,"0, 0","3, 2","6, 4","6, 3",15,3,6,9
10,Suen,"5, 3","4, 3","5, 2","0, 0",14,1,6,8

In [20]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 4,
 'Objective value': 7800.0,
 'Solve time': '0.019252 seconds',
 'Branches': 593,
 'Conflicts': 9}

In [21]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/family_practice.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Family Practice Calendar', 
                     output_dir = '../output/november_25/family_practice',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-11-03 to 2025-11-28
Processing 33 schedule entries...
Processed schedule data for 18 unique dates
Filtered to 150 leave requests for this department
Processing 150 leave requests...
Processed leave requests for 64 unique dates
Filtered to 18 inpatient assignments for this department
Processing 18 inpatient assignments...
Processed inpatient assignments for 105 unique dates
Found 4 weeks containing scheduled dates
Calendar saved to: ../output/november_25/family_practice/calendar.html