# Generating the September 2025 Schedule 
**This notebook builds the September 2025 schedule for Internal Medicine, Pediatrics, and Family Practice using the scheduler.**

In [1]:
## Setup and Imports
import sys
from pathlib import Path
import os
import pandas as pd
from datetime import date, timedelta

In [2]:
# Add project root (one level up from 'notebooks') to sys.path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

In [3]:
# Import our scheduling engine
from engine.engine import create_im_schedule, create_peds_schedule, create_fp_schedule

# Import calendar generation
from utils.calendar_formatter import create_html_calendar

## Internal Medicine Schedule

In [4]:
schedule_df, provider_summary_df, solution_status = create_im_schedule(
    config_path = '../config/internal_medicine.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    start_date = date(2025, 9, 1),
    end_date = date(2025, 10, 3),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:52:13,460 - engine.engine - INFO - Creating schedule for Internal Medicine from 2025-09-01 to 2025-10-03
2025-06-22 13:52:13,461 - engine.engine - INFO - Parsing input files
2025-06-22 13:52:13,470 - engine.engine - INFO - Building calendar
2025-06-22 13:52:13,470 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:52:13,470 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:52:13,505 - engine.engine - INFO - Found optimal solution with min_providers = 4
2025-06-22 13:52:13,507 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 4

In [5]:
schedule_df.to_csv('../output/september_25/internal_medicine/schedule_df.csv', index = False)
schedule_df

,date,day_of_week,session,providers,count
0,2025-09-02,Tuesday,morning,"Mcnett,Selig,Stewart,Wadlin",4
1,2025-09-02,Tuesday,afternoon,"Mcnett,Miles,Selig,Stewart",4
2,2025-09-03,Wednesday,morning,"Mcnett,Mcrae,Stewart,Tanay,Wadlin",5
3,2025-09-03,Wednesday,afternoon,"Mcnett,Mcrae,Stewart,Tanay",4
4,2025-09-04,Thursday,afternoon,"Mcnett,Mcrae,Selig,Tanay,Wadlin",5
5,2025-09-05,Friday,morning,"Mcnett,Mcrae,Selig,Tanay,Wadlin",5
6,2025-09-05,Friday,afternoon,"Mcnett,Mcrae,Selig,Tanay,Wadlin",5
7,2025-09-08,Monday,morning,"Mcnett,Rafferty,Selig,Tanay,Wadlin",5
8,2025-09-08,Monday,afternoon,"Mcnett,Rafferty,Selig,Tanay,Wadlin",5
9,2025-09-09,Tuesday,morning,"Mcnett,Rafferty,Selig,Stewart,Tanay",5
10,2025-09-09,Tuesday,afternoon,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
11,2025-09-10,Wednesday,morning,"Mcnett,Mcrae,Rafferty,Stewart,Wadlin",5
12,2025-09-10,Wednesday,afternoon,"Mcnett,Mcrae,Rafferty,Stewart,Wadlin",5
13,2025-09-11,Thursday,afternoon,"Mcnett,Mcrae,Rafferty,Selig,Tanay",5
14,2025-09-12,Friday,morning,"Mcnett,Mcrae,Rafferty,Selig,Stewart",5
15,2025-09-12,Friday,afternoon,"Mcnett,Mcrae,Rafferty,Selig,Tanay",5
16,2025-09-15,Monday,morning,"Mcnett,Mcrae,Miles,Rafferty,Tanay",5
17,2025-09-15,Monday,afternoon,"Mcnett,Mcrae,Rafferty,Stewart,Tanay",5
18,2025-09-16,Tuesday,morning,"Mcnett,Miles,Rafferty,Selig,Tanay",5
19,2025-09-16,Tuesday,afternoon,"Mcnett,Miles,Rafferty,Selig,Tanay",5
20,2025-09-17,Wednesday,morning,"Bornstein,Mcnett,Mcrae,Rafferty,Selig",5
21,2025-09-17,Wednesday,afternoon,"Mcnett,Mcrae,Rafferty,Selig,Stewart",5
22,2025-09-18,Thursday,afternoon,"Bornstein,Mcnett,Rafferty,Selig,Tanay",5
23,2025-09-19,Friday,morning,"Mcnett,Mcrae,Rafferty,Selig,Stewart",5
24,2025-09-19,Friday,afternoon,"Mcnett,Mcrae,Rafferty,Stewart,Tanay",5
25,2025-09-22,Monday,morning,"Bornstein,Mcrae,Rafferty,Selig,Stewart",5
26,2025-09-22,Monday,afternoon,"Mcnett,Rafferty,Selig,Stewart,Tanay",5
27,2025-09-23,Tuesday,morning,"Mcnett,Rafferty,Selig,Stewart,Tanay",5
28,2025-09-23,Tuesday,afternoon,"Bornstein,Mcnett,Rafferty,Selig,Tanay",5
29,2025-09-24,Wednesday,morning,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
30,2025-09-24,Wednesday,afternoon,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
31,2025-09-25,Thursday,afternoon,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
32,2025-09-26,Friday,morning,"Bornstein,Mcnett,Rafferty,Selig,Stewart",5
33,2025-09-26,Friday,afternoon,"Bornstein,Mcnett,Mcrae,Rafferty,Selig",5
34,2025-09-29,Monday,morning,"Mcnett,Mcrae,Rafferty,Selig,Stewart",5
35,2025-09-29,Monday,afternoon,"Bornstein,Mcnett,Rafferty,Selig,Stewart",5
36,2025-09-30,Tuesday,morning,"Bornstein,Mcnett,Mcrae,Rafferty,Selig",5
37,2025-09-30,Tuesday,afternoon,"Mcnett,Mcrae,Rafferty,Selig,Stewart",5
38,2025-10-01,Wednesday,morning,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
39,2025-10-01,Wednesday,afternoon,"Mcnett,Mcrae,Rafferty,Tanay,Wadlin",5
40,2025-10-02,Thursday,afternoon,"Bornstein,Mcnett,Mcrae,Miles,Rafferty",5
41,2025-10-03,Friday,morning,"Bornstein,Mcnett,Rafferty,Selig,Stewart",5
42,2025-10-03,Friday,afternoon,"Mcnett,Rafferty,Selig,Tanay,Wadlin",5

In [6]:
provider_summary_df.to_csv('../output/september_25/internal_medicine/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_36,week_37,week_38,week_39,week_40,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Bornstein,"0, 0","0, 0","2, 1","4, 2","4, 2",10,3,5,5
1,Mcnett,"7, 4","9, 6","9, 6","8, 5","9, 6",42,1,18,24
2,Mcrae,"5, 3","6, 3","6, 2","5, 2","6, 4",28,3,12,16
3,Miles,"1, 1","0, 0","3, 2","0, 0","1, 1",5,5,2,3
4,Rafferty,"0, 0","9, 6","9, 6","9, 6","9, 6",36,1,16,20
5,Selig,"5, 3","6, 3","6, 4","6, 4","6, 4",29,2,14,15
6,Stewart,"4, 4","4, 2","4, 2","4, 3","4, 2",20,2,11,9
7,Tanay,"5, 3","6, 4","6, 4","6, 5","3, 2",26,3,9,17
8,Wadlin,"5, 3","5, 3","0, 0","3, 2","3, 2",16,5,7,9

In [7]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 4,
 'Objective value': 4000.0,
 'Solve time': '0.018619 seconds',
 'Branches': 938,
 'Conflicts': 10}

In [8]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/internal_medicine.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Internal Medicine Calendar', 
                     output_dir = '../output/september_25/internal_medicine',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-09-02 to 2025-10-03
Processing 43 schedule entries...
Processed schedule data for 24 unique dates
Filtered to 132 leave requests for this department
Processing 132 leave requests...
Processed leave requests for 62 unique dates
Filtered to 11 inpatient assignments for this department
Processing 11 inpatient assignments...
Processed inpatient assignments for 70 unique dates
Found 5 weeks containing scheduled dates
Calendar saved to: ../output/september_25/internal_medicine/calendar.html

## Pediatric Schedule

In [9]:
schedule_df, provider_summary_df, call_summary_df, solution_status = create_peds_schedule(
    config_path = '../config/pediatrics.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    start_date = date(2025, 8, 31),
    end_date = date(2025, 10, 4),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:52:13,558 - engine.engine - INFO - Creating schedule for Pediatric from 2025-08-31 to 2025-10-04
2025-06-22 13:52:13,559 - engine.engine - INFO - Parsing input files
2025-06-22 13:52:13,566 - engine.engine - INFO - Building calendar
2025-06-22 13:52:13,566 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:52:13,567 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:52:13,597 - engine.engine - WARNING - No feasible solution found with min_providers = 4
2025-06-22 13:52:13,597 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 3
2025-06-22 13:52:13,626 - engine.engine - WARNING - No feasible solution found with min_providers = 3
2025-06-22 13:52:13,626 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 2
2025-06-22 13:52:13,671 - engine.engine - INFO - Found optimal solution with min_providers = 2
2025-06-22 13:52:13,675 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 2

In [10]:
schedule_df.head(50)

          date day_of_week    session                        providers  count
0   2025-08-31      Sunday       call                         Menachof    NaN
1   2025-09-01      Monday       call                         Menachof    NaN
2   2025-09-02     Tuesday    morning   Bedele,Menachof,Miller,Sridhar    4.0
3   2025-09-02     Tuesday  afternoon            Bedele,Miller,Sridhar    3.0
4   2025-09-02     Tuesday       call                           Bedele    NaN
5   2025-09-03   Wednesday    morning   Bedele,Carrasco,Miller,Sridhar    4.0
6   2025-09-03   Wednesday  afternoon          Carrasco,Miller,Sridhar    3.0
7   2025-09-03   Wednesday       call                           Miller    NaN
8   2025-09-04    Thursday  afternoon   Bedele,Carrasco,Snyder,Sridhar    4.0
9   2025-09-04    Thursday       call                          Sridhar    NaN
10  2025-09-05      Friday    morning   Menachof,Miller,Snyder,Sridhar    4.0
11  2025-09-05      Friday  afternoon           Menachof,Miller,Snyder    3.0
12  2025-09-05      Friday       call                            Mador    NaN
13  2025-09-06    Saturday       call                            Mador    NaN
14  2025-09-07      Sunday       call                          Sridhar    NaN
15  2025-09-08      Monday    morning     Bedele,Miller,Snyder,Sridhar    4.0
16  2025-09-08      Monday  afternoon             Bedele,Miller,Snyder    3.0
17  2025-09-08      Monday       call                           Bedele    NaN
18  2025-09-09     Tuesday    morning     Bedele,Miller,Snyder,Sridhar    4.0
19  2025-09-09     Tuesday  afternoon   Menachof,Miller,Snyder,Sridhar    4.0
20  2025-09-09     Tuesday       call                         Menachof    NaN
21  2025-09-10   Wednesday    morning     Mador,Menachof,Miller,Snyder    4.0
22  2025-09-10   Wednesday  afternoon              Mador,Miller,Snyder    3.0
23  2025-09-10   Wednesday       call                           Miller    NaN
24  2025-09-11    Thursday  afternoon      Bedele,Mador,Snyder,Sridhar    4.0
25  2025-09-11    Thursday       call                             Shin    NaN
26  2025-09-12      Friday    morning            Bedele,Snyder,Sridhar    3.0
27  2025-09-12      Friday  afternoon   Bedele,Menachof,Snyder,Sridhar    4.0
28  2025-09-12      Friday       call                         Carrasco    NaN
29  2025-09-13    Saturday       call                         Carrasco    NaN
30  2025-09-14      Sunday       call                             Shin    NaN
31  2025-09-15      Monday    morning     Bedele,Mador,Menachof,Snyder    4.0
32  2025-09-15      Monday  afternoon     Bedele,Mador,Menachof,Snyder    4.0
33  2025-09-15      Monday       call                         Menachof    NaN
34  2025-09-16     Tuesday    morning    Bedele,Carrasco,Miller,Snyder    4.0
35  2025-09-16     Tuesday  afternoon    Bedele,Carrasco,Miller,Snyder    4.0
36  2025-09-16     Tuesday       call                           Bedele    NaN
37  2025-09-17   Wednesday    morning    Bedele,Carrasco,Miller,Snyder    4.0
38  2025-09-17   Wednesday  afternoon  Carrasco,Menachof,Miller,Snyder    4.0
39  2025-09-17   Wednesday       call                           Powell    NaN
40  2025-09-18    Thursday  afternoon       Bedele,Mador,Miller,Snyder    4.0
41  2025-09-18    Thursday       call                           Miller    NaN
42  2025-09-19      Friday    morning              Mador,Miller,Snyder    3.0
43  2025-09-19      Friday  afternoon                     Mador,Snyder    2.0
44  2025-09-19      Friday       call                          Sridhar    NaN
45  2025-09-20    Saturday       call                          Sridhar    NaN
46  2025-09-21      Sunday       call                         Carrasco    NaN
47  2025-09-22      Monday    morning             Bedele,Miller,Snyder    3.0
48  2025-09-22      Monday  afternoon             Bedele,Miller,Snyder    3.0
49  2025-09-22      Monday       call                           Miller    NaN

In [11]:
# Get the current providers for session 9/3 PM
mask = (schedule_df['date'] == date(2025, 9, 3)) & (schedule_df['session'] == 'afternoon')
current_providers = schedule_df.loc[mask, 'providers'].iloc[0]

# Add Snyder
schedule_df.loc[mask, 'providers'] = current_providers + ',Snyder'

# Update provider_summary_df count for that day 
current_count = schedule_df.loc[mask, 'count'].iloc[0]
schedule_df.loc[mask, 'count'] = current_count + 1

# Get the current providers for session 10/3 AM
mask = (schedule_df['date'] == date(2025, 10, 3)) & (schedule_df['session'] == 'morning')
current_providers = schedule_df.loc[mask, 'providers'].iloc[0]

# Add Snyder
schedule_df.loc[mask, 'providers'] = current_providers + ',Snyder'

# Update provider_summary_df count for that day 
current_count = schedule_df.loc[mask, 'count'].iloc[0]
schedule_df.loc[mask, 'count'] = current_count + 1

In [12]:
schedule_df.to_csv('../output/september_25/pediatrics/schedule_df.csv', index = False)

In [13]:
provider_summary_df.to_csv('../output/september_25/pediatrics/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_36,week_37,week_38,week_39,week_40,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Bedele,"4, 3","6, 3","6, 5","6, 4","6, 4",28,3,14,14
1,Carrasco,"3, 2","0, 0","4, 4","6, 4","5, 3",18,4,9,9
2,Mador,"0, 0","3, 2","5, 3","0, 0","3, 2",11,4,4,7
3,Menachof,"3, 2","3, 2","3, 2","0, 0","3, 3",12,5,5,7
4,Miller,"6, 4","6, 6","6, 4","5, 3","0, 0",23,5,12,11
5,Snyder,"3, 3","9, 6","9, 6","9, 6","7, 6",37,2,16,21
6,Sridhar,"6, 4","6, 3","0, 0","0, 0","3, 2",15,4,7,8

In [14]:
call_summary_df.to_csv('../output/september_25/pediatrics/call_summary_df.csv', index = False)
call_summary_df

   provider  week_35  week_36  week_37  week_38  week_39  week_40  total_call
0    Bedele        0        1        1        1        2        1           6
1  Carrasco        0        0        2        1        1        1           5
2     Mador        0        2        0        0        2        0           4
3  Menachof        1        1        1        1        0        0           4
4    Miller        0        1        1        1        1        2           6
5    Powell        0        0        0        1        1        1           3
6      Shin        0        0        2        0        0        1           3
7    Snyder        0        0        0        0        0        0           0
8   Sridhar        0        2        0        2        0        0           4

In [15]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 2,
 'Objective value': 6902.0,
 'Solve time': '0.018791 seconds',
 'Branches': 86,
 'Conflicts': 0}

In [16]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/pediatrics.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Pediatrics Calendar', 
                     output_dir = '../output/september_25/pediatrics',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-08-31 to 2025-10-04
Processing 78 schedule entries...
Processed schedule data for 35 unique dates
Filtered to 179 leave requests for this department
Processing 179 leave requests...
Processed leave requests for 75 unique dates
Filtered to 25 inpatient assignments for this department
Processing 25 inpatient assignments...
Processed inpatient assignments for 133 unique dates
Found 5 weeks containing scheduled dates
Calendar saved to: ../output/september_25/pediatrics/calendar.html

## Family Practice Schedule

In [17]:
schedule_df, provider_summary_df, solution_status = create_fp_schedule(
    config_path = '../config/family_practice.yml',
    leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
    inpatient_path = '../data/inpatient_sep_dec_25.csv',
    peds_schedule_path = '../output/september_25/pediatrics/schedule_df.csv',
    start_date = date(2025, 9, 1),
    end_date = date(2025, 10, 3),
    min_staffing_search = True,
    initial_min_providers = 4,
    random_seed = 42
)

2025-06-22 13:52:13,748 - engine.engine - INFO - Creating schedule for Family Practice from 2025-09-01 to 2025-10-03
2025-06-22 13:52:13,749 - engine.engine - INFO - Parsing input files
2025-06-22 13:52:13,756 - engine.engine - INFO - Loading pediatric schedule
2025-06-22 13:52:13,758 - engine.engine - INFO - Successfully loaded pediatric schedule with 78 rows
2025-06-22 13:52:13,758 - engine.engine - INFO - Building calendar
2025-06-22 13:52:13,758 - engine.engine - INFO - Beginning iterative min_providers search, starting with 4
2025-06-22 13:52:13,759 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 4
2025-06-22 13:52:13,781 - engine.engine - WARNING - No feasible solution found with min_providers = 4
2025-06-22 13:52:13,781 - engine.engine - INFO - Attempting to solve with min_providers_per_session = 3
2025-06-22 13:52:13,820 - engine.engine - INFO - Found optimal solution with min_providers = 3
2025-06-22 13:52:13,823 - engine.engine - INFO - Successfully found solution with highest possible min_providers = 3

In [18]:
schedule_df.to_csv('../output/september_25/family_practice/schedule_df.csv', index = False)
schedule_df

          date day_of_week    session                     providers  count
0   2025-09-02     Tuesday    morning            Mullenix,Shin,Suen      3
1   2025-09-02     Tuesday  afternoon            Mullenix,Shin,Suen      3
2   2025-09-03   Wednesday    morning              Austin,Shin,Suen      3
3   2025-09-03   Wednesday  afternoon              Austin,Shin,Suen      3
4   2025-09-04    Thursday  afternoon          Austin,Mullenix,Suen      3
5   2025-09-05      Friday    morning         Austin,Brush,Mullenix      3
6   2025-09-05      Friday  afternoon         Austin,Brush,Mullenix      3
7   2025-09-08      Monday    morning          Gelman,Mullenix,Suen      3
8   2025-09-08      Monday  afternoon          Gelman,Mullenix,Suen      3
9   2025-09-09     Tuesday    morning   Austin,Gelman,Mullenix,Suen      4
10  2025-09-09     Tuesday  afternoon    Austin,Bia,Gelman,Mullenix      4
11  2025-09-10   Wednesday    morning        Austin,Bia,Powell,Shin      4
12  2025-09-10   Wednesday  afternoon        Austin,Bia,Powell,Shin      4
13  2025-09-11    Thursday  afternoon          Austin,Bia,Shin,Suen      4
14  2025-09-12      Friday    morning      Brush,Mullenix,Shin,Suen      4
15  2025-09-12      Friday  afternoon    Brush,Gelman,Mullenix,Suen      4
16  2025-09-15      Monday    morning      Austin,Bia,Mullenix,Suen      4
17  2025-09-15      Monday  afternoon      Austin,Bia,Mullenix,Suen      4
18  2025-09-16     Tuesday    morning          Bia,Powell,Shin,Suen      4
19  2025-09-16     Tuesday  afternoon         Austin,Bia,Salay,Shin      4
20  2025-09-17   Wednesday    morning        Austin,Salay,Shin,Suen      4
21  2025-09-17   Wednesday  afternoon    Austin,Mullenix,Salay,Suen      4
22  2025-09-18    Thursday  afternoon    Austin,Mullenix,Salay,Suen      4
23  2025-09-19      Friday    morning    Brush,Mullenix,Powell,Shin      4
24  2025-09-19      Friday  afternoon    Brush,Mullenix,Powell,Shin      4
25  2025-09-22      Monday    morning          Austin,Mullenix,Suen      3
26  2025-09-22      Monday  afternoon    Austin,Mullenix,Salay,Suen      4
27  2025-09-23     Tuesday    morning      Austin,Bia,Mullenix,Suen      4
28  2025-09-23     Tuesday  afternoon      Austin,Bia,Mullenix,Suen      4
29  2025-09-24   Wednesday    morning     Bia,Gelman,Mullenix,Salay      4
30  2025-09-24   Wednesday  afternoon         Gelman,Mullenix,Salay      3
31  2025-09-25    Thursday  afternoon       Austin,Bia,Gelman,Salay      4
32  2025-09-26      Friday    morning          Bia,Brush,Salay,Suen      4
33  2025-09-26      Friday  afternoon          Bia,Brush,Salay,Suen      4
34  2025-09-29      Monday    morning   Gelman,Mullenix,Powell,Suen      4
35  2025-09-29      Monday  afternoon   Austin,Gelman,Mullenix,Suen      4
36  2025-09-30     Tuesday    morning      Austin,Powell,Salay,Suen      4
37  2025-09-30     Tuesday  afternoon    Mullenix,Powell,Salay,Shin      4
38  2025-10-01   Wednesday    morning    Austin,Mullenix,Salay,Shin      4
39  2025-10-01   Wednesday  afternoon  Austin,Gelman,Mullenix,Salay      4
40  2025-10-02    Thursday  afternoon      Mullenix,Salay,Shin,Suen      4
41  2025-10-03      Friday    morning      Brush,Gelman,Powell,Suen      4
42  2025-10-03      Friday  afternoon       Brush,Gelman,Salay,Suen      4

In [19]:
provider_summary_df.to_csv('../output/september_25/family_practice/provider_summary_df.csv', index = False)
provider_summary_df

,provider,week_36,week_37,week_38,week_39,week_40,total_sessions,monday_or_friday_off,total_AM,total_PM
0,Austin,"5, 3","5, 4","6, 3","5, 4","4, 2",25,5,10,15
1,Bia,"0, 0","4, 3","4, 4","6, 3","0, 0",14,5,6,8
2,Brush,"2, 2","2, 2","2, 2","2, 2","2, 2",10,5,5,5
3,Gelman,"0, 0","5, 4","0, 0","3, 2","5, 2",13,3,5,8
4,Mullenix,"5, 3","6, 4","6, 3","6, 6","6, 3",29,3,12,17
5,Powell,"0, 0","2, 2","3, 2","0, 0","4, 2",9,4,6,3
6,Salay,"0, 0","0, 0","4, 3","6, 3","6, 4",16,4,5,11
7,Shin,"4, 4","4, 2","5, 3","0, 0","3, 2",16,5,8,8
8,Suen,"5, 4","6, 3","6, 3","6, 4","6, 3",29,2,14,15

In [20]:
solution_status

{'Status': 'OPTIMAL',
 'Minimum providers per session': 3,
 'Objective value': 7000.0,
 'Solve time': '0.019516 seconds',
 'Branches': 579,
 'Conflicts': 1}

In [21]:
create_html_calendar(schedule_df = schedule_df,
                     config_path = '../config/family_practice.yml',
                     leave_requests_path = '../data/leave_requests_sep_dec_25.csv',
                     inpatient_path = '../data/inpatient_sep_dec_25.csv',
                     title = 'Family Practice Calendar', 
                     output_dir = '../output/september_25/family_practice',
                     filename = 'calendar.html')

Converting date column to datetime...
Calendar range: 2025-09-02 to 2025-10-03
Processing 43 schedule entries...
Processed schedule data for 24 unique dates
Filtered to 136 leave requests for this department
Processing 136 leave requests...
Processed leave requests for 63 unique dates
Filtered to 16 inpatient assignments for this department
Processing 16 inpatient assignments...
Processed inpatient assignments for 91 unique dates
Found 5 weeks containing scheduled dates
Calendar saved to: ../output/september_25/family_practice/calendar.html